// =============================================================================
//  Imports
// =============================================================================
import markdownit from 'markdown-it';
import complianceHtml from './compliance-html.js';

// ---------------------------------------------------------------------------
//  Markdown parser setup (markdown-it with HTML passthrough enabled)
// ---------------------------------------------------------------------------
var md = markdownit({
  html: true,
});

// =============================================================================
//  Configuration
// =============================================================================
const API_BASE = 'http://127.0.0.1:5000';

// ---------------------------------------------------------------------------
//  Built-in test plans (hardcoded at build time)
// ---------------------------------------------------------------------------
const testPlans = [
  {
    key: 'presets',
    name: 'Presets & Assignees',
    description: 'Test preset loading, task population, and the assignee feature.',
    markdown: `## Preset System

- [ ] Click **Summon** on a preset — tasks should populate the list
- [ ] Click **DELETE** on a preset — preset should disappear
- [ ] Verify preset tasks get created with correct names

## Assignee Feature

- [ ] Change the assignee dropdown on a task
- [ ] Refresh the page — assignee should persist
- [ ] Verify the dropdown shows all options: No one, Liam, Zippy, Ben, Eli, Anika, Janie, Global`
  },
];

// ---------------------------------------------------------------------------
//  Global state
// ---------------------------------------------------------------------------
let activeTestPlan = 'compliance';

// ---------------------------------------------------------------------------
//  DOM references (populated after DOMContentLoaded)
// ---------------------------------------------------------------------------
const todo_list = document.getElementById("todo_list");
const todo_input = document.getElementById("todo_input");
const preset_list = document.getElementById("preset_list");

// Available assignee names used in dropdowns
const assigneeOptions = ["No one", "Liam", "Zippy", "Ben", "Eli", "Anika", "Janie", "Global"];


// =============================================================================
//  Markdown Checkbox Post-Processing
// =============================================================================

/**
 * Scans a container element for <li> items that contain [ ] or [x] text
 * at the start and replaces them with real, interactive <input type="checkbox">
 * elements. This works on any HTML, whether generated by markdown-it or
 * embedded as pre-rendered HTML strings.
 *
 * @param {HTMLElement} container - The DOM container to process (e.g. the
 *   rendered test-plan content div).
 */
function makeCheckboxesInteractive(container) {
  if (!container) return;

  const listItems = container.querySelectorAll('li');
  listItems.forEach((li) => {
    // Extract the text content to detect checkbox markers
    const text = li.textContent || '';

    const uncheckedMatch = text.match(/^\s*\[ \]/);
    const checkedMatch = text.match(/^\s*\[x\]/i);

    if (!uncheckedMatch && !checkedMatch) return;

    const marker = uncheckedMatch ? '[ ]' : checkedMatch[0];
    const markerIdx = text.indexOf(marker);

    // -------------------------------------------------------------------
    //  Build a real checkbox <input>
    // -------------------------------------------------------------------
    const cb = document.createElement('input');
    cb.type = 'checkbox';
    cb.classList.add('md-checkbox');
    cb.checked = !!checkedMatch;

    // Toggle the checkbox visual state (strikethrough) on click
    cb.addEventListener('change', () => {
      const contentSpan = li.querySelector('.md-task-text');
      if (contentSpan) {
        contentSpan.style.textDecoration = cb.checked ? 'line-through' : 'none';
        contentSpan.style.opacity = cb.checked ? '0.5' : '1';
      }
    });

    // -------------------------------------------------------------------
    //  Preserve any existing HTML inside the <li> while stripping the
    //  marker text.
    // -------------------------------------------------------------------
    const wrapper = document.createElement('span');
    wrapper.classList.add('md-task-item');

    // Grab the innerHTML and splice out the marker portion
    let html = li.innerHTML;
    html = html.replace(/^\s*\[[ xX]\]/, '').replace(/^\s*/, '');
    wrapper.innerHTML = html;

    // Wrap the remaining content in a span so we can style completed tasks
    const contentSpan = document.createElement('span');
    contentSpan.classList.add('md-task-text');
    contentSpan.innerHTML = wrapper.innerHTML;

    if (cb.checked) {
      contentSpan.style.textDecoration = 'line-through';
      contentSpan.style.opacity = '0.5';
    }

    // Rebuild the <li> contents
    li.innerHTML = '';
    li.appendChild(cb);
    li.appendChild(contentSpan);
  });
}


// =============================================================================
//  Test Plan Lifecycle (open, render, manage)
// =============================================================================

/**
 * Fetches user-created test plans from the backend and merges them into the
 * in-memory testPlans array (idempotent — duplicates are skipped).
 */
async function initTestPlansFromDB() {
  try {
    const response = await fetch(`${API_BASE}/test_plans`);
    const result = await response.json();
    if (result.test_plans) {
      for (const plan of result.test_plans) {
        const exists = testPlans.some(p => p.key === plan.key);
        if (!exists) {
          plan.fromDB = true;
          testPlans.push(plan);
        }
      }
    }
  } catch (err) {
    console.log('Could not load test plans from DB:', err);
  }
}

/**
 * Opens the currently-selected test plan, renders its markdown (or uses
 * pre-rendered HTML if available), and post-processes the content to make
 * task-list checkboxes interactive.
 */
function openTestPlan() {
  const selectorScreen = document.getElementById("test-plan-selector-screen");
  const contentScreen = document.getElementById("test-plan-content-screen");
  const title = document.getElementById("test-plan-title");
  const content = document.getElementById("test-plans-content");

  const plan = testPlans.find(p => p.key === activeTestPlan);
  if (!plan) return;

  title.textContent = plan.name;

  // Render markdown to HTML, or use pre-rendered HTML if present.
  // Some "htmlContent" values are actually raw markdown — detect and
  // render those through markdown-it as well.
  if (plan.htmlContent) {
    const isMarkdown = /^#{1,6}\s/m.test(plan.htmlContent)
      || /^-\s\[[ xX]\]/m.test(plan.htmlContent)
      || !/<[a-z][\s\S]*>/i.test(plan.htmlContent);

    if (isMarkdown) {
      content.innerHTML = md.render(plan.htmlContent);
    } else {
      content.innerHTML = plan.htmlContent;
    }
  } else {
    content.innerHTML = md.render(plan.markdown);
  }

  // Post-process: replace [ ] and [x] markers with interactive checkboxes
  makeCheckboxesInteractive(content);

  selectorScreen.style.display = "none";
  contentScreen.style.display = "flex";
}

/**
 * Returns to the test-plan selector list.
 */
window.backToSelector = function() {
  const selectorScreen = document.getElementById("test-plan-selector-screen");
  const contentScreen = document.getElementById("test-plan-content-screen");

  selectorScreen.style.display = "flex";
  contentScreen.style.display = "none";
};

/**
 * Toggles the test-plans slide-in panel open / closed.
 */
window.toggleTestPlans = function() {
  const panel = document.getElementById("test-plans-panel");
  if (!panel) return;
  panel.classList.toggle("open");
  if (panel.classList.contains("open")) {
    backToSelector();
    initTestPlansFromDB().then(() => renderTestPlanSelector());
  }
};

/**
 * Renders the list of available test plans into the selector sidebar.
 * Plans loaded from the DB get an extra delete (X) button.
 */
function renderTestPlanSelector() {
  const selector = document.getElementById("test-plan-selector");
  if (!selector) return;
  selector.innerHTML = '';
  testPlans.forEach(plan => {
    const btn = document.createElement("button");
    btn.className = "test-plan-btn";

    const nameSpan = document.createElement("span");
    nameSpan.className = "test-plan-btn-name";
    nameSpan.textContent = plan.name;

    const descSpan = document.createElement("span");
    descSpan.className = "test-plan-btn-desc";
    descSpan.textContent = plan.description;

    btn.appendChild(nameSpan);
    btn.appendChild(descSpan);

    // DB-sourced plans get a delete control
    if (plan.fromDB) {
      const deleteBtn = document.createElement("span");
      deleteBtn.className = "test-plan-delete";
      deleteBtn.textContent = "X";
      deleteBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        deleteTestPlan(plan.key);
      });
      btn.appendChild(deleteBtn);
    }

    btn.addEventListener("click", () => {
      activeTestPlan = plan.key;
      openTestPlan();
    });

    selector.appendChild(btn);
  });
}

/**
 * Sends a delete request to the backend and removes the plan from local state.
 */
async function deleteTestPlan(key) {
  await fetch(`${API_BASE}/delete_test_plan`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ key: key }),
  });

  const idx = testPlans.findIndex(p => p.key === key);
  if (idx !== -1) {
    testPlans.splice(idx, 1);
  }
  renderTestPlanSelector();
}


// =============================================================================
//  Create Test Plan Modal
// =============================================================================

window.openCreateTestPlanModal = function() {
  document.getElementById("create-test-plan-modal").classList.remove("hidden");
  document.getElementById("test-plan-title-input").focus();
};

window.cancelCreateTestPlanModal = function() {
  document.getElementById("create-test-plan-modal").classList.add("hidden");
  document.getElementById("create-test-plan-error").classList.add("hidden");
  document.getElementById("test-plan-title-input").value = "";
  document.getElementById("test-plan-desc-input").value = "";
  document.getElementById("test-plan-markdown-input").value = "";
};

window.confirmCreateTestPlanModal = async function() {
  const title = document.getElementById("test-plan-title-input").value.trim();
  const description = document.getElementById("test-plan-desc-input").value.trim();
  const markdown = document.getElementById("test-plan-markdown-input").value.trim();
  const errEl = document.getElementById("create-test-plan-error");

  if (!title) {
    errEl.textContent = "Thou must name thy test plan!";
    errEl.classList.remove("hidden");
    return;
  }

  if (!markdown) {
    errEl.textContent = "Markdown content is required, traveler!";
    errEl.classList.remove("hidden");
    return;
  }

  errEl.classList.add("hidden");

  const response = await fetch(`${API_BASE}/create_test_plan`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      title: title,
      description: description,
      markdown: markdown
    }),
  });

  const result = await response.json();

  if (result.status === "error") {
    errEl.textContent = result.message || "Creation failed!";
    errEl.classList.remove("hidden");
    return;
  }

  const newPlan = result.test_plan;
  newPlan.fromDB = true;
  testPlans.push(newPlan);
  renderTestPlanSelector();

  document.getElementById("create-test-plan-modal").classList.add("hidden");
  document.getElementById("test-plan-title-input").value = "";
  document.getElementById("test-plan-desc-input").value = "";
  document.getElementById("test-plan-markdown-input").value = "";
};


// =============================================================================
//  Presets (right sidebar)
// =============================================================================

/**
 * Fetches all presets from the backend and renders them.
 */
async function display_presets() {
  const response = await fetch(`${API_BASE}/allpresets`);
  const result = await response.json();

  for (const preset of result.presets) {
    create_preset(preset.name, preset.author, preset.desc);
  }
}

/**
 * Creates a preset card in the DOM (right sidebar).
 */
function create_preset(preset_name, preset_author, preset_desc) {
  const preset_container = document.createElement("div");
  preset_container.classList.add("preset_container");

  const title = document.createElement("h1");
  title.textContent = `${preset_name} Author: ${preset_author}`;

  const description = document.createElement("p");
  description.textContent = preset_desc;
  description.classList.add("preset_desc");

  const summon_button = document.createElement("button");
  summon_button.textContent = "Summon";
  summon_button.classList.add("preset_summon");

  const delete_button = document.createElement("button");
  delete_button.textContent = "DELETE";
  delete_button.classList.add("delete-button");

  summon_button.addEventListener("click", () => load_preset(preset_name));
  delete_button.addEventListener("click", () => {
    preset_container.remove();
    preset_delete(preset_name);
  });

  preset_container.appendChild(title);
  preset_container.appendChild(description);
  preset_container.appendChild(summon_button);
  preset_container.appendChild(delete_button);

  preset_list.appendChild(preset_container);
}

/**
 * Loads all tasks from a preset and adds them to the todo list.
 */
async function load_preset(preset_name) {
  const response = await fetch(`${API_BASE}/presets`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ "preset_name": preset_name })
  });

  const result = await response.json();

  for (const task of result.tasks) {
    CreateTask(task, false, "No one");
  }
}


// =============================================================================
//  Task CRUD (main todo list)
// =============================================================================

/**
 * Creates a task DOM element without hitting the database. Used during
 * initial page load (get_all) to rebuild the UI from existing DB rows.
 *
 * @param {string}  task_name   - Name / text of the task
 * @param {boolean} completed   - Completion state
 * @param {string}  assigned_to - Currently-assigned person
 */
async function create_task_DBSkip(task_name, completed, assigned_to) {
  let inputValue;
  if (!task_name) {
    if (todo_input.value === "") {
      alert("Please actually type something bro");
      return;
    }
    inputValue = todo_input.value;
  } else {
    inputValue = task_name;
  }

  if (!completed) {
    completed = false;
  }

  if (!assigned_to) {
    assigned_to = "No one";
  }

  const span = document.createElement("span");
  span.textContent = inputValue;

  const todo_item = document.createElement("li");
  todo_item.classList.add("todo_item");

  const checkbox = document.createElement("input");
  checkbox.type = "checkbox";
  checkbox.checked = completed;

  if (completed) {
    span.style.textDecoration = "line-through";
  }

  checkbox.addEventListener("change", () => {
    span.style.textDecoration = checkbox.checked ? "line-through" : "none";
    checkedOff(inputValue);
  });

  const delete_btn = document.createElement("button");
  delete_btn.textContent = "Delete";
  delete_btn.classList.add("delete-button");

  delete_btn.addEventListener("click", () => {
    todo_list.removeChild(todo_item);
    delete_element(inputValue);
  });

  const assignee_dropdown = create_assignee_dropdown(inputValue, assigned_to);

  todo_item.appendChild(checkbox);
  todo_item.appendChild(span);
  todo_item.appendChild(assignee_dropdown);
  todo_item.appendChild(delete_btn);

  todo_list.appendChild(todo_item);
  todo_input.value = "";
}

/**
 * Creates a task both in the database and in the DOM. Used when the user
 * types a new task and clicks submit.
 *
 * @param {string}  task_name   - Name / text of the task
 * @param {boolean} completed   - Completion state
 * @param {string}  assigned_to - Currently-assigned person
 */
window.CreateTask = async function CreateTask(task_name, completed, assigned_to) {
  let inputValue;

  if (!task_name) {
    if (todo_input.value === "") {
      alert("Please actually type something bro");
      return;
    }
    inputValue = todo_input.value;
  } else {
    inputValue = task_name;
  }

  if (!completed) {
    completed = false;
  }

  if (!assigned_to) {
    assigned_to = "No one";
  }

  const status = await create_element(inputValue, completed);

  if (status === "error") {
    alert("You tried to create a task that already existed!");
    return;
  }

  const span = document.createElement("span");
  span.textContent = inputValue;

  const todo_item = document.createElement("li");
  todo_item.classList.add("todo_item");

  const checkbox = document.createElement("input");
  checkbox.type = "checkbox";
  checkbox.checked = completed;

  if (completed) {
    span.style.textDecoration = "line-through";
  }

  checkbox.addEventListener("change", () => {
    span.style.textDecoration = checkbox.checked ? "line-through" : "none";
    checkedOff(inputValue);
  });

  const delete_btn = document.createElement("button");
  delete_btn.textContent = "Delete";
  delete_btn.classList.add("delete-button");

  delete_btn.addEventListener("click", () => {
    todo_list.removeChild(todo_item);
    delete_element(inputValue);
  });

  const assignee_dropdown = create_assignee_dropdown(inputValue, assigned_to);

  todo_item.appendChild(checkbox);
  todo_item.appendChild(span);
  todo_item.appendChild(assignee_dropdown);
  todo_item.appendChild(delete_btn);

  todo_list.appendChild(todo_item);
  todo_input.value = "";
}

/**
 * Builds a custom-styled assignee dropdown for a task.
 */
function create_assignee_dropdown(task_name, assigned_to) {
  const wrapper = document.createElement("label");
  wrapper.classList.add("assignee_dropdown_wrapper");

  const labelText = document.createElement("span");
  labelText.textContent = "Assigned to";
  labelText.classList.add("assignee_label");

  const select = document.createElement("select");
  select.classList.add("assignee_dropdown");
  select.setAttribute("aria-label", `Assign ${task_name} to someone`);

  for (const person of assigneeOptions) {
    const option = document.createElement("option");
    option.value = person;
    option.textContent = person;
    select.appendChild(option);
  }

  select.value = assigneeOptions.includes(assigned_to) ? assigned_to : "No one";

  select.addEventListener("change", () => {
    assign_task(task_name, select.value);
  });

  wrapper.appendChild(labelText);
  wrapper.appendChild(select);

  return wrapper;
}


// =============================================================================
//  API Helpers (Flask backend)
// =============================================================================

/**
 * Fetches all tasks from the backend and populates the DOM.
 */
async function get_all() {
  const response = await fetch(`${API_BASE}/gettasks`);
  const result = await response.json();
  const tasks = result.tasks;

  for (const task of tasks) {
    create_task_DBSkip(task.task_name, task.completed, task.assigned_to);
  }
}

/**
 * Creates a task row in the database.
 * @returns {string} "error" if a duplicate was found, otherwise undefined.
 */
async function create_element(task_name) {
  const payload = { "task_name": task_name };

  const response = await fetch(`${API_BASE}/addelement`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });

  const result = await response.json();

  if (result.status === "error") {
    return "error";
  }

  console.log(result);
}

/**
 * Deletes a task row from the database.
 */
async function delete_element(task_name) {
  const payload = { "task_name": task_name };

  const response = await fetch(`${API_BASE}/deletetask`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });

  const result = await response.json();
  console.log(result);
}

/**
 * Toggles a task's completed status in the database.
 */
async function checkedOff(task_name) {
  const payload = { "task_name": task_name };

  const response = await fetch(`${API_BASE}/checkoff`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });

  const result = await response.json();
  console.log(result);
}

/**
 * Updates a task's assigned person in the database.
 */
async function assign_task(task_name, assigned_to) {
  const payload = { "task_name": task_name, "assigned_to": assigned_to };

  const response = await fetch(`${API_BASE}/assigntask`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });

  const result = await response.json();
  console.log(result);
}

/**
 * Deletes a preset and its associated tasks from the database.
 */
async function preset_delete(preset_name) {
  const payload = { "preset_name": preset_name };

  const response = await fetch(`${API_BASE}/delete_preset`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });

  const result = await response.json();
  console.log(result);
}


// =============================================================================
//  Application bootstrap
// =============================================================================
document.addEventListener("DOMContentLoaded", () => {
  get_all()
  display_presets()
  initTestPlansFromDB()
})
